name: Tests (govc)

permissions:
  contents: read
  actions: read

on:
  push:
    branches: main
  pull_request:
    branches: main

concurrency:
  group: govmomi-govc-tests-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  govc-tests:
    name: Run govc Tests
    strategy:
      fail-fast: false
      matrix:
        go-version: ["1.23"]
        platform: [ubuntu-latest]
        cmd: [govc-test]
        experimental: [false]
        timeout: [20]

    runs-on: ${{ matrix.platform }}
    continue-on-error: ${{ matrix.experimental }}
    timeout-minutes: ${{ matrix.timeout }}

    steps:
      - name: Check Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5.4.0
        with:
          go-version: ${{ matrix.go-version }}
        id: go

      - name: Restore Go Cache
        uses: actions/cache@d4323d4df104b026a6aa633fdb11d772146be0bf # v4.2.2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ matrix.go-version }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-${{ matrix.go-version }}-

      - name: Run ${{ matrix.cmd }}
        run: |
          make ${{ matrix.cmd }}

      - name: Debug on Failure
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@e5c7151931ca95bad1c6f4190c730ecf8c7dde48 # v3.19

  govc-docs:
    name: Verify Updated Docs
    strategy:
      matrix:
        go-version: ["1.22"]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    timeout-minutes: 3
    steps:
      - name: Check Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5.4.0
        with:
          go-version: ${{ matrix.go-version }}
        id: go

      - name: Restore Go Cache
        uses: actions/cache@d4323d4df104b026a6aa633fdb11d772146be0bf # v4.2.2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ matrix.go-version }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-${{ matrix.go-version }}-

      - name: Run "make doc"
        run: |
          make doc
          if [ -z "$(git status --porcelain)" ]; then
            echo "govc/USAGE.md is up2date..."
          else
            echo "dirty working directory (diff):"
            git --no-pager diff
            echo "::error file=govc/USAGE.md::Run make doc to update USAGE.md"
            exit 1
          fi
